# K-Nearest Neighbour Classification Algorithm

###### Supervised learning algorithm used for classification.
###### Euclidean distance = sq.root((x2-x1)^2 + (y2-y1)^2)

Parameter K should be ODD and must not too low and be lesser than 20% of the total number of data points.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('./iris_dataset.csv')
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

        target  
0  Iris-setosa  
1  Iris-setosa  
2  Iris-setosa  
3  Iris-setosa  
4  Iris-setosa

In [4]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [5]:
df.shape

(150, 5)

In [7]:
df['target'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: target, dtype: int64

In [9]:
x = df.iloc[:, :-1]  # similar to x = df[['sepal_len','sepal_width','petal_len','petal_width']]
y = df.iloc[:, -1]

In [12]:
print(type(x), x.shape)
x.head()

<class 'pandas.core.frame.DataFrame'> (150, 4)


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [13]:
print(type(y), y.shape)
y.head()

<class 'pandas.core.series.Series'> (150,)


0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: target, dtype: object

In [14]:
from sklearn.model_selection import train_test_split

In [21]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(112, 4)
(38, 4)
(112,)
(38,)


In [22]:
from sklearn.neighbors import KNeighborsClassifier

In [23]:
m1 = KNeighborsClassifier(n_neighbors=7)
m1.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [24]:
# Accuracy
print("Training Score = ", m1.score(x_train, y_train))
print("Testing Score = ", m1.score(x_test, y_test))

Training Score =  0.9910714285714286
Testing Score =  0.9473684210526315


In [26]:
y_pred_m1 = m1.predict(x_test)
y_pred_m1

array(['Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa'], dtype=object)

In [27]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [30]:
print(confusion_matrix(y_test, y_pred_m1))
print(classification_report(y_test, y_pred_m1))
print("Accuracy=",accuracy_score(y_test, y_pred_m1))

[[17  0  0]
 [ 0 11  2]
 [ 0  0  8]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        17
Iris-versicolor       1.00      0.85      0.92        13
 Iris-virginica       0.80      1.00      0.89         8

       accuracy                           0.95        38
      macro avg       0.93      0.95      0.94        38
   weighted avg       0.96      0.95      0.95        38

Accuracy= 0.9473684210526315
